### ISSUE TITLE
Install command on NPM/GitHub readme refers to incorrect package

### ISSUE THREAD

**Issue by kyledyr** [apexad/homebridge-eufy-robovac#12]
The readme files on GitHub and NPM for v 1.2.1 and 1.2.0-beta.5 have the following install command shown:

> npm install -g homebridge-mysmartblinds-bridge

Presumably this is not the correct package reference, as I believe it should be homebridge-eufy-robovac

**Comment by apexad** [comment]
Whoops, changed text to reflect config.schema.json and copied from my other plugin. Fixing it now.
