### ISSUE TITLE
Vacuum Cleaner reports as off when it is actually on

### ISSUE THREAD

**Issue by apexad** [apexad/homebridge-eufy-robovac#13]
Just wanted to put this here in case anyone else experiences this issue.

This causes a problem with the 'turn off to return home' feature of the plugin. There is a workaround where you can simply click it back on and then Off again and the Vacuum will return to the base station after several beeps.  However, this is not ideal.

In reviewing why this is occurring it seems like the get function is for some reason returning `undefined` at times and I have yet to figure out why.

**Comment by MonsterEnergy-wtf** [comment]
I realized the same issue that devices are not shown as active.

Also I suggest to test this plugin more with Linux. Not sure what it causes but by homebridge server still says disconnected to eufies (I own 3 of them) until I restart it. After that the eufies are connected. 
May it be that the plugin causes some unexpected behavior to connections? Maybe they cannot be refreshed or something like that?

As I mentioned: once I restart the service homebridge, everything works as expected. I don't have any other plugins installed than eufy robovacs.

**Comment by apexad** [comment]
> I realized the same issue that devices are not shown as active.
> 
> Also I suggest to test this plugin more with Linux. Not sure what it causes but by homebridge server still says disconnected to eufies (I own 3 of them) until I restart it. After that the eufies are connected.
> May it be that the plugin causes some unexpected behavior to connections? Maybe they cannot be refreshed or something like that?
> 
> As I mentioned: once I restart the service homebridge, everything works as expected. I don't have any other plugins installed than eufy robovacs.

Don’t think Linux has anything to do with it. It is related to how the NodeJS Tuya API is used by this plugin.

Also, keep in mind that only 1 connection to the Vacuum is allowed at a time, so opening the app on your phone or tablet can cause unexpected results. Otherwise, yes I have found that restarting homebridge fetches the status of the Vacuum in a different way and this may then allow Home app to correctly report them as on.

Just to note, if you have a HomePod, giving it Turn on/Turn off commands work as expected. This is just when using the Home app. You will need to then the Vacuum back on (even when it is actually on but incorrectly reporting as off), then turn it off to send it back home. Should not need to restart Homebridge.

**Comment by MonsterEnergy-wtf** [comment]
For me it seems that version 1.3.1 fixed the issue with wrong status.

Also I restart homebridge every 15 minutes to pull data correctly. Automation works as expected.

**Comment by apexad** [comment]
This is not resolved.  It is because you are restarting Homebridge every 15 minutes which is something I do not recommend.

**Comment by MonsterEnergy-wtf** [comment]
Yes, but I disabled the automatic restart of homebridge for several days and it turned out that the Eufies became unresponsible. So I basically return back to the workaround I had in the past and hope that unresponsible devices are gone. It is definitely not the best way to resolve it but it is better to make it that way than having trouble with Homebridge and the Eufy Plugin.

**Comment by apexad** [comment]
I'm woking on a total re-write of this homebridge plugin to fix this issue.  No ETA, but soon.
