### ISSUE TITLE
Option to emulate "Switch" instead of "Fan"

### ISSUE THREAD

**Issue by AdamDempsey** [apexad/homebridge-eufy-robovac#15]
I know that HomeKit doesn't currently officially support Vacuums which is why it appears as a Fan but is it possible to have an option to appear as a Switch instead as I have multiple real fans in the same room and when I use siri to switch them on and off in bulk my RoboVac also switches on.

**Comment by apexad** [comment]
Sure, this should be fairly easy. Will work on it as soon as I can. Otherwise PRs are welcome.
