### ISSUE TITLE
Device descriptions are gone in overview

### ISSUE THREAD

**Issue by MonsterEnergy-wtf** [apexad/homebridge-eufy-robovac#17]
With version 1.3.1 the issue with the wrong status is gone but now I'm facing the issue that the device's custom names are gone.
![WrongNames](https://user-images.githubusercontent.com/61805098/84246468-f530f000-ab06-11ea-9c77-b1a17946ded2.jpg)

The details of each tile is correct. So basically the display name in tiles are ignored. This causes Homekit to display wrong names. In my case I have three RoboVacs which are now all the same.
This is a display issue only.

![WrongName2](https://user-images.githubusercontent.com/61805098/84246914-961fab00-ab07-11ea-86be-1dd681b220bd.jpg)

**Comment by MonsterEnergy-wtf** [comment]
Also there is a mixture in localization. "Find Eufy Robovac" is English while the status is in German "Aus" (off).

**Comment by apexad** [comment]
I am not sure about the 'Find' issue, that localization was never changed, but v1.3.2 should correct the name of the Vacuums.
