### ISSUE TITLE
Accessory not showing in Hoobs

### ISSUE THREAD

**Issue by vypergts** [apexad/homebridge-eufy-robovac#19]
My vac was showing in 1.4. Since updating to 2.0.1, it won't show up at all in either Hoobs or Homekit. Log states:

6/25/2020, 2:06:07 PM The requested accessory "Eufy RoboVac" was not registered by any plugin.
6/25/2020, 2:06:07 PM Your config.json is requesting the accessory "Eufy RoboVac" which has not been published by any installed plugins.

My JSON config is:

        {
            "accessory": "Eufy RoboVac",
            "plugin_map": {
                "plugin_name": "homebridge-eufy-robovac",
                "index": 0
            },
            "name": "RoboVac",
            "hideFindButton": true,
            "hideErrorSensor": true,
            "useSwitchService": false,
            "debugLog": false,
            "deviceId": "78041805XXXXXXXXXX",
            "localKey": "e41XXXXXXXXXXXXXX"
        }

**Comment by apexad** [comment]
2.0.0 May require homebridge 1.0 now and hoobs may not be updated yet. Please check with them to confirm and re-open if they say it is updated.
