### ISSUE TITLE
Battery state - Apple Home

### ISSUE THREAD

**Issue by HumanSkunk** [apexad/homebridge-eufy-robovac#23]
Hi, finally managed to get the plugin working with a bit of help from Reddit. Works great!

Only one 'issue' within the Homebridge app you can see the Charging state and percentage, is that feature usable within Apple Home? As I cant see any button/feature for it. The only entry that appears is the 3 bundled accessories including the off/on the buzzer and the motion sensor.

Is this a limitation of apple home or am I missing something?

**Comment by apexad** [comment]
The Battery Percent is show on the main switch if you click on the Settings Icon in the bottom right.
![IMG_FF583345F78B-1 2](https://user-images.githubusercontent.com/1437332/91643417-ea8c4580-e9e7-11ea-81c3-db7f7f1cc57c.jpeg)
