### ISSUE TITLE
Can't find the right combination of devId & localKey

### ISSUE THREAD

**Issue by dallombra** [apexad/homebridge-eufy-robovac#25]
Hi there, when trying to find the devId/LocalKey combo, I can't seem to find exactly what's needed. Looking at the log file, I have the following

- device_key --> 16 digits alphanumeric
- local_code --> 16 digits alphanumeric
- device_id --> 36 digits alphanumeric (including 4 dashes - )

These are the only things I can find in the logs, but no combinations of those actually result in a successful connection. 

Any ideas?

To add more context, I'm using the latest version of Bluestack on Windows 10 and using the linked APK for the EUFY Home app

**Comment by apexad** [comment]
No need to make the same issue/comment in 3 different places. deleted 1 comment, closing this.  Will assist on https://github.com/joshstrange/eufy-robovac/issues/13
