### ISSUE TITLE
Individually work, but fail when more than one Robovac is connected

### ISSUE THREAD

**Issue by ghost** [apexad/homebridge-eufy-robovac#27]
Hi,
I have three robovacs, a G10, 30C and 15C Max. I have the device ID and Localkey for each which i sniffed from bluestacks. When i load them in individually, they work. However, when i try and have more than one vacuum identified it throws out the following error in Homebridge status Log:

"Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)"

By connecting more than one at a time, none of them work. I have to completely reinstall the plugin when there is a failure. Here is the config file (please excuse the stupid names):
{
    "bridge": {
        "name": "Homebridge removed",
        "username": "removed",
        "port": removed,
        "pin": "removed"
    },
      "accessories": [
        {
            "name": "Claude",
            "deviceId": "70636387a4cf12e129ee",
            "localKey": "361ba1588facd637",
            "hideFindButton": false,
            "hideErrorSensor": false,
            "useSwitchService": false,
            "debugLog": false,
            "accessory": "Eufy RoboVac"
        },
        {
            "name": "Effy",
            "deviceId": "51066360cc50e33205ae",
            "localKey": "8d2631d6498d4e70",
            "hideFindButton": false,
            "hideErrorSensor": false,
            "useSwitchService": false,
            "debugLog": false,
            "accessory": "Eufy RoboVac"
        },
        {
            "name": "Verity",
            "deviceId": "bf8064d5a3e5f3ef17tsod",
            "localKey": "2e812507ccb1ce71",
            "hideFindButton": false,
            "hideErrorSensor": false,
            "useSwitchService": false,
            "debugLog": false,
            "accessory": "Eufy RoboVac"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-grey",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "PS4WakerPlatform",
            "name": "PS4",
            "accessories": [
                {
                    "serial": "03274523235940406",
                    "model": "CUH-1216A",
                    "ip": "192.168.1.87",
                    "credentials": "/home/pi/.ps4-wake.credentials.json"
                }
            ],
            "global": {
                "timeout": 10000
            }
        }
    ]
}

*As an aside, you'll notice the G10 (Verity) has a 22 digit hex - perhaps a new feature for the newer models?

Any help or guidance you can give would be great. I'm pretty new to all this, but i've seen elsewhere people with more than one vacuum so i think it's possible.

Thanks

**Comment by apexad** [comment]
Connect to Tuya API for Eufy Robovac Vacuum cleaners is not ideal.  In my experience it barely works with 1 vacuum and there are issues with the app when the plugin is running.

Perhaps try adding one, restart homebridge, wait a few minutes, add a second, restart, wait a few minutes, add a 3rd.

Otherwise, I could implement some random timeouts to stager the connects or something, but there may still be errors, just less frequently.

**Comment by ghost** [comment]
It seems very sporadic. Today, i could get two (!) working, but only when i had already turned them on and then closed the Eufyhome app. Minutes later, all were unresponsive.

**Comment by MonsterEnergy-wtf** [comment]
This is strange. I have 3 Robovac30c and it works. 
Are they usable when using the app from Eufy for them?

**Comment by ghost** [comment]
They work flawlessly from the Eufy app, and from Alexa and elsewhere. Just trying to get them into the HomeKit ecosphere so I can bin off Alexa but it’s a bit of an uphill struggle at the moment.

Would you share your config so I can make sure I’m not doing anything daft?

**Comment by apexad** [comment]
@pinityoufairy Try using `2.1.2-beta.0` and see if it works any better. I've made small small change to add a random delay.  Curious if that will help.

**Comment by pinityoufairy** [comment]
@apexad apologies for being a rampant n00b but ...how do I install the beta? I’m familiar with smashing “Sudo npm install -g homebridge-eufy-robovac“ into the terminal, but that’s about as techy as I get. I’m an engineer, but a concrete and steel one!

**Comment by ghost** [comment]
Ok, i installed 2.1.2 beta.0 and it made no difference. Same errors.

"Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)"

 I can't get the 30C or the 15C Max to respond at all. The G10 did respond when installed as the sole accessory, but when i subsequently install a second vacuum neither respond. I restarted homekit each time between installing each vacuum. All remain controllable from the eufy app (so are definitely on and connected to the network).

**Comment by apexad** [comment]
Bummer

**Comment by apexad** [comment]
Try `2.1.2-beta.1`.  I've changed up the configuration a bit, but also added an called `timeoutDuration` which can be set in homebridge ui under advanced options.  Try setting it to something like 5 (as it was 2 by default before) and see if that helps.

**EDIT:** use `homebridge-eufy-robovac@2.1.2-beta.2` instead

**Comment by ghost** [comment]
Hi, thanks for your efforts so far.
I uninstalled and then reinstalled homebridge-eufy-robovac@2.1.2-beta.2. I've also only set one vacuum up and it's not working with just one. 

but i'm getting the following (same) error:

Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Connecting...
Robovac Error {}
Robovac Error {}
Robovac Error {}
Robovac Error {}
Robovac Error {}
Disconnected!
Disconnected!
Disconnected!
Disconnected!
Disconnected!
Disconnected!

**Comment by apexad** [comment]
Just want to confirm you do not have the Eufy app open on any device right? Even in the background?

**Comment by ghost** [comment]
Correct, it is closed on iphones and ipad. I do have sharing set up with my partner through the eufy app, but it is closed on her devices too.

**Comment by apexad** [comment]
@joshstrange I am planning to re-write this plugin to not store connections and possibly turn it into a platform to better support multiple vacuums. Asking again if you are able to transfer this to me?

**Comment by joshstrange** [comment]
@apexad Sorry I missed your other request to transfer, I've been meaning to ask you about transferring since I'm not active. I will transfer this and the other repo to you now.

**Comment by joshstrange** [comment]
@apexad It's not letting me transfer because you have a fork of this I think. You might just be able to re-name your version and then I can transfer
![Screen Shot 2020-12-23 at 1 23 25 PM](https://user-images.githubusercontent.com/462796/103026500-16e14a00-4522-11eb-80f4-76a3c61a7d03.png)

**Comment by joshstrange** [comment]
Same deal for the base library, if you can rename quickly I can transfer now. I'm about to have to leave my house for a few hours so I can do it later if we can't resolve this within the next 5-10min.

**Comment by apexad** [comment]
@joshstrange Try again, I just deleted both

**Comment by joshstrange** [comment]
@apexad Done and done. Both have been transferred from my end. Thank you for taking these projects and thank you for running the support for as long as you have. I should have reached out about transferring a long time ago seeing how you have been doing all the work. If there is anything else I missed let me know and I'll transfer it as well.

**Comment by ghost** [comment]
@joshstrange  @apexad  I’m very excited to see where you guys go with this, and thanks for your support to date!

**Comment by mreassassin** [comment]
I'm in the same boat with the errors and multiple vacs. Also looking forward to the upgrades!  Thanks!

**Comment by sierralx** [comment]
Connecting...
Connected!
Robovac Error {}
Disconnected!
Robovac Error {}
Robovac Error {}
Robovac Error {}

**Comment by MonsterEnergy-wtf** [comment]
https://github.com/apexad/homebridge-eufy-robovac/issues/28#issuecomment-753294378

**Comment by apexad** [comment]
Interesting stuff here, but closing in favor of #30
