### ISSUE TITLE
Intermittent Connected!, Disconnected!, Robovac Error {}

### ISSUE THREAD

**Issue by sierralx** [apexad/homebridge-eufy-robovac#28]
Connecting...
Connected!
Robovac Error {}
Disconnected!
Robovac Error {}
Robovac Error {}
Robovac Error {}

**Comment by MonsterEnergy-wtf** [comment]
I resolved this issue with 3(!) Robovacs by restarting the homebridge every 15 minutes. 
For me it is working fine.

I remember, that @apexad (correct me if I'm wrong)mentioned something in the past that the initial discovery of the robovacs works differently than the "keep alive and are you still there?" mode.

I guess this is why my robovacs work fine.

You could give it a try. It may help to ser where the plugin can be improved.

**Comment by apexad** [comment]
Similar to #27, but in any case it has to do with he number of connections allowed to the tuna platform for the Eufy Robovac vacuums.  Not much I can do to resolve this without a re-write, which I am planning but don't have an ETA.  Refer to #27 for updates on this though as that is where I will log changes to how this plugin connects.

**Comment by treforparr** [comment]
I'm stoned have a problem with this gonna be fixed I had it working last night and then started playing up
