### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by Pau1Mc** [apexad/homebridge-eufy-robovac#40]
Has stopped being functional in homekit

**Comment by apexad** [comment]
duplicate

**Comment by Pau1Mc** [comment]
Update resolves the issue, great work!
Thanks for maintaining this



On 17 Mar 2022, at 03:37, Alex Martin ***@***.***> wrote:

﻿
Closed #40.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
