### ISSUE TITLE
Suggestion: Alternate way to get device ID and local key without emulator

### ISSUE THREAD

**Issue by ip-rob** [apexad/homebridge-eufy-robovac#42]
Not an issue, just a suggestion. I didn't want to install an emulator and didn't have an Android device available, so I used the python script located here: https://gitlab.com/Rjevski/eufy-device-id-and-local-key-grabber

Running this script from my ubuntu VM was very simple and output the device ID and key to use in the plugin. 

Thought that approach might be worth adding to the Wiki.

Thanks for the plugin work!

Rob

**Comment by ip-rob** [comment]
Closing this as I see it is in the eufy-robovac repository in the open issue, thus redundant. Sorry.

**Comment by seldridge1** [comment]
I’m sure it isn’t the safest route, but for what it’s worth, I was able to use Storm Sniffer (https://apps.apple.com/us/app/storm-sniffer-packet-capture/id1610958307) to find my devId and localKey.
