### ISSUE TITLE
Robovac X8

### ISSUE THREAD

**Issue by sichii97** [apexad/homebridge-eufy-robovac#44]
Hey,

it's not possible to use it for the robovac x8 actually.
I'm not able to claim the local ID.

**Comment by andyp2234** [comment]
hi I have the local id and device id of robotic x8 hybrid , it finds the device and ip address but times out

**Comment by apexad** [comment]
I'm not looking to confirm/add new Eufy vacuums to this plugin at this time.  I think other plugins exist that may work. I may update the README soon with suggestions for newer plugins
