### ISSUE TITLE
Find My Robot Not Working

### ISSUE THREAD

**Issue by HenryGelderbloem** [apexad/homebridge-eufy-robovac#54]
It appears I do not have the Find My Robot functionality in the Home app at all.

I added "hideFindButton": false to my json configuration but after a restart it still does not display.

No logs displayed even with debug logging enabled.

**Comment by HenryGelderbloem** [comment]
#56

**Comment by apexad** [comment]
PR merged. but not published yet.  However, I know different versions of this plugin now exist.  I may unpublished this plugin completely soon, but for now at least cleaning up the Issues and stuff so closing this one.
