### ISSUE TITLE
Error Sensor Missing

### ISSUE THREAD

**Issue by HenryGelderbloem** [apexad/homebridge-eufy-robovac#55]
I am not getting the Motion Sensor in the Home app. 

I added "hideErrorSensor": false to the JSON configuration for the plugin and it still does not appear after a restart.

No logs even with debug logging enabled.

**Comment by apexad** [comment]
Duplicate of https://github.com/apexad/homebridge-eufy-robovac/issues/45
But, as mentioned I may archive this plugin if I can find newer alternatives exist
