### ISSUE TITLE
Eufy S1 Pro vacuum: Switch pauses cleaning when turned on; Turning switch off does nothing

### ISSUE THREAD

**Issue by mda30** [apexad/homebridge-eufy-robovac#59]
For the Eufy S1 Pro vacuum this plugin creates a switch that pauses the current cleaning when the switch is turned on (then the switch turns itself off), and when the switch is turned off by the user it does nothing. The other switches (Find Robot, etc) also do not work.

**Comment by apexad** [comment]
Similar to https://github.com/apexad/homebridge-eufy-robovac/issues/45 in that there seems to be demand to return many more functions back.  I may do this but I may also do research into newer plugins and make recommendations.  Additionally, this may be different when switching to native ios 18 https://github.com/apexad/homebridge-eufy-robovac/issues/60

Closing this issue for now as I think the ask is covered by other issues.
